name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2025-vs2026]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.3

      - name: Get compiler # Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gnucobol

      - name: Get compiler # macOS
        if: runner.os == 'macOS'
        run: brew install gnucobol

      - name: Get compiler # Windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gnucobol
          cache: false

      - name: Build
        if: runner.os != 'Windows'
        run: |
          cobc -x -o coboculator calculator.cbl

      - name: Build # Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cobc -conf=/mingw64/share/gnucobol/config/default.conf -x -static -o coboculator.exe calculator.cbl

      - name: Upload
        uses: actions/upload-artifact@v7.0.1
        with:
          name: app-${{ matrix.os }}
          path: |
            coboculator
            coboculator.exe
          if-no-files-found: error